/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/bootstrap-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the first admin user
         * @description One-shot endpoint for installing the first admin in a fresh deployment. Idempotent: returns 409 once any admin exists. Disabled unless ``SEEDBANK_BOOTSTRAP_TOKEN`` is configured; the request must present the matching token.
         */
        post: operations["bootstrap_admin_api_v1_auth_bootstrap_admin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_api_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/{provider}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Login */
        get: operations["oauth_login_api_v1_auth_oauth__provider__login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Callback */
        get: operations["oauth_callback_api_v1_auth_oauth__provider__callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Role */
        patch: operations["update_role_api_v1_users__user_id__role_patch"];
        trace?: never;
    };
    "/api/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Keys */
        get: operations["list_keys_api_v1_api_keys_get"];
        put?: never;
        /** Create Key */
        post: operations["create_key_api_v1_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Key */
        delete: operations["revoke_key_api_v1_api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        /** Register Model */
        post: operations["register_model_api_v1_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["get_model_api_v1_models__model_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Model Status */
        patch: operations["update_model_status_api_v1_models__model_id__patch"];
        trace?: never;
    };
    "/api/v1/models/{model_id}/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Model Performance
         * @description Aggregated performance for one model.
         *
         *     Two sources merged into one envelope:
         *
         *     * ``offline_metrics`` — Phase 7 ``model_metrics`` rows written by the
         *       experiment runner (always available).
         *     * ``rows`` — Phase 8 ClickHouse ``fact_inference`` aggregates
         *       (returns empty + a degradation ``note`` until that table exists).
         */
        get: operations["model_performance_api_v1_models__model_id__performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traffic-splits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Splits */
        get: operations["list_splits_api_v1_traffic_splits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Replace Splits
         * @description Atomically replace the traffic splits for one segment.
         */
        patch: operations["replace_splits_api_v1_traffic_splits_patch"];
        trace?: never;
    };
    "/api/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit images for detection + classification
         * @description Upload one or more images. The server stores them in MinIO, creates a `scan_batch` (status=`pending`), and dispatches Celery tasks. The response is HTTP 202 with the batch envelope; clients poll `GET /api/v1/batches/{id}` for results.
         *
         *     The `model_id` override is restricted to `ai_developer` and `admin`.
         */
        post: operations["analyze_api_v1_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches */
        get: operations["list_batches_api_v1_batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_api_v1_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}/image-urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Batch Image Urls
         * @description Short-lived presigned URLs for the batch's images.
         *
         *     The client pairs these with the normalized bounding boxes from
         *     ``GET /batches/{id}`` to render detections over the original image —
         *     the bytes are served straight from object storage, never proxied
         *     through the API.
         */
        get: operations["get_batch_image_urls_api_v1_batches__batch_id__image_urls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_v1_datasets_get"];
        put?: never;
        /** Create Dataset */
        post: operations["create_dataset_api_v1_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_api_v1_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_v1_datasets__dataset_id__items_get"];
        put?: never;
        /** Add Items */
        post: operations["add_items_api_v1_datasets__dataset_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["list_experiments_api_v1_experiments_get"];
        put?: never;
        /** Create Experiment */
        post: operations["create_experiment_api_v1_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment */
        get: operations["get_experiment_api_v1_experiments__experiment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Probes DB, Redis, MinIO, and ClickHouse. Returns degraded statuses
         *     per-component so the operator can tell what's broken from one ping.
         *
         *     Production-model readiness is added in Phase 5 once the model
         *     manager exists.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiKeyCreateIn */
        ApiKeyCreateIn: {
            /** Name */
            name: string;
            /** Scopes */
            scopes?: string[];
            /** Expires At */
            expires_at?: string | null;
        };
        /**
         * ApiKeyOut
         * @description Returned on **creation only**. The plaintext `key` is included exactly
         *     once and never retrievable again.
         */
        ApiKeyOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Prefix */
            prefix: string;
            /** Scopes */
            scopes: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at?: string | null;
            /** Last Used At */
            last_used_at?: string | null;
            /** Revoked At */
            revoked_at?: string | null;
            /** Key */
            key?: string | null;
        };
        /**
         * BatchDetailOut
         * @description Full nested envelope for ``GET /batches/{id}`` — batch → images
         *     → inferences → detections, eager-loaded by the repository.
         */
        BatchDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            status: components["schemas"]["BatchStatus"];
            source: components["schemas"]["BatchSource"];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Supplier Id */
            supplier_id?: string | null;
            /**
             * Image Count
             * @default 0
             */
            image_count: number;
            /** Error Message */
            error_message?: string | null;
            location_source?: components["schemas"]["LocationSource"] | null;
            /** Gps Lat */
            gps_lat?: string | null;
            /** Gps Long */
            gps_long?: string | null;
            /** Geo City */
            geo_city?: string | null;
            /** Geo Country Code */
            geo_country_code?: string | null;
            /** Images */
            images?: components["schemas"]["ScanImageOut"][];
        };
        /**
         * BatchOut
         * @description Lightweight batch summary — the ``POST /analyze`` response and
         *     each row of the ``GET /batches`` page.
         *
         *     ``image_count`` is populated by the service layer (a count query or
         *     ``len(files)``); it is *not* a column on ``scan_batches``.
         */
        BatchOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            status: components["schemas"]["BatchStatus"];
            source: components["schemas"]["BatchSource"];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Supplier Id */
            supplier_id?: string | null;
            /**
             * Image Count
             * @default 0
             */
            image_count: number;
        };
        /**
         * BatchSource
         * @enum {string}
         */
        BatchSource: "api" | "web" | "sdk";
        /**
         * BatchStatus
         * @enum {string}
         */
        BatchStatus: "pending" | "running" | "succeeded" | "failed" | "partial";
        /** Body_analyze_api_v1_analyze_post */
        Body_analyze_api_v1_analyze_post: {
            /**
             * Files
             * @description One or more images
             */
            files: string[];
            /** Supplier Id */
            supplier_id?: string | null;
            /** Seed Type Id */
            seed_type_id?: string | null;
            /** Model Id */
            model_id?: string | null;
            /** Gps Lat */
            gps_lat?: number | string | null;
            /** Gps Long */
            gps_long?: number | string | null;
            /** Country Code */
            country_code?: string | null;
        };
        /**
         * BootstrapAdminIn
         * @description Payload for ``POST /auth/bootstrap-admin``.
         *
         *     The ``bootstrap_token`` field is a shared secret rotated out of the
         *     environment after first-admin creation; the password rules match
         *     ``RegisterIn`` so the resulting admin can immediately log in.
         */
        BootstrapAdminIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name?: string | null;
            /** Bootstrap Token */
            bootstrap_token: string;
        };
        /**
         * DatasetCreateIn
         * @description Request body for ``POST /datasets``.
         */
        DatasetCreateIn: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * DatasetItemCreateIn
         * @description One item inside a bulk-add request.
         *
         *     ``image_storage_key`` references an object the caller has already
         *     uploaded to MinIO ``seedbank-datasets`` (presigned PUT or
         *     ``scripts/upload_dataset.py``). The server does not fetch or
         *     validate the bytes synchronously — the experiment runner does that
         *     when it dereferences the item.
         *
         *     ``ground_truth`` is a free-form JSON document; the experiment runner
         *     enforces the schema (``{"kind": "detection", "boxes": [...]}`` or
         *     ``{"kind": "classification", "label": "good"}``).
         */
        DatasetItemCreateIn: {
            /** Image Storage Key */
            image_storage_key: string;
            /** Ground Truth */
            ground_truth?: {
                [key: string]: unknown;
            } | null;
            /** Checksum */
            checksum?: string | null;
        };
        /**
         * DatasetItemOut
         * @description Listing entry for a :class:`DatasetItem`.
         */
        DatasetItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Storage Key */
            image_storage_key: string;
            /** Ground Truth */
            ground_truth?: {
                [key: string]: unknown;
            } | null;
            /** Checksum */
            checksum?: string | null;
        };
        /**
         * DatasetItemsAddedOut
         * @description Response body for the bulk-add endpoint.
         */
        DatasetItemsAddedOut: {
            /** Added */
            added: number;
        };
        /**
         * DatasetItemsBulkIn
         * @description Request body for ``POST /datasets/{id}/items``.
         */
        DatasetItemsBulkIn: {
            /** Items */
            items: components["schemas"]["DatasetItemCreateIn"][];
        };
        /**
         * DatasetOut
         * @description List + detail response for a :class:`Dataset`.
         */
        DatasetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Created By */
            created_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Item Count
             * @default 0
             */
            item_count: number;
        };
        /** Envelope[ApiKeyOut] */
        Envelope_ApiKeyOut_: {
            data: components["schemas"]["ApiKeyOut"];
        };
        /** Envelope[BatchDetailOut] */
        Envelope_BatchDetailOut_: {
            data: components["schemas"]["BatchDetailOut"];
        };
        /** Envelope[BatchOut] */
        Envelope_BatchOut_: {
            data: components["schemas"]["BatchOut"];
        };
        /** Envelope[DatasetItemsAddedOut] */
        Envelope_DatasetItemsAddedOut_: {
            data: components["schemas"]["DatasetItemsAddedOut"];
        };
        /** Envelope[DatasetOut] */
        Envelope_DatasetOut_: {
            data: components["schemas"]["DatasetOut"];
        };
        /** Envelope[ExperimentDetailOut] */
        Envelope_ExperimentDetailOut_: {
            data: components["schemas"]["ExperimentDetailOut"];
        };
        /** Envelope[ExperimentSummaryOut] */
        Envelope_ExperimentSummaryOut_: {
            data: components["schemas"]["ExperimentSummaryOut"];
        };
        /** Envelope[MeOut] */
        Envelope_MeOut_: {
            data: components["schemas"]["MeOut"];
        };
        /** Envelope[MessageOut] */
        Envelope_MessageOut_: {
            data: components["schemas"]["MessageOut"];
        };
        /** Envelope[ModelOut] */
        Envelope_ModelOut_: {
            data: components["schemas"]["ModelOut"];
        };
        /** Envelope[ModelPerformanceOut] */
        Envelope_ModelPerformanceOut_: {
            data: components["schemas"]["ModelPerformanceOut"];
        };
        /** Envelope[TokenPair] */
        Envelope_TokenPair_: {
            data: components["schemas"]["TokenPair"];
        };
        /** Envelope[list[ImageUrlOut]] */
        Envelope_list_ImageUrlOut__: {
            /** Data */
            data: components["schemas"]["ImageUrlOut"][];
        };
        /** Envelope[list[TrafficSplitOut]] */
        Envelope_list_TrafficSplitOut__: {
            /** Data */
            data: components["schemas"]["TrafficSplitOut"][];
        };
        /**
         * ExperimentCreateIn
         * @description Request body for ``POST /experiments``.
         *
         *     ``name`` is human-readable; ``model_id`` and ``dataset_id`` are the
         *     only required references. The worker resolves both during dispatch.
         */
        ExperimentCreateIn: {
            /** Name */
            name: string;
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
        };
        /**
         * ExperimentDetailOut
         * @description Detail view — same as summary plus the embedded result count.
         */
        ExperimentDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            status: components["schemas"]["ExperimentStatus"];
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Summary Metrics */
            summary_metrics?: {
                [key: string]: unknown;
            } | null;
            /** Mlflow Run Id */
            mlflow_run_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by?: string | null;
            /**
             * Result Count
             * @default 0
             */
            result_count: number;
        };
        /**
         * ExperimentStatus
         * @enum {string}
         */
        ExperimentStatus: "pending" | "running" | "succeeded" | "failed";
        /**
         * ExperimentSummaryOut
         * @description List-row + create-response shape — small enough to ship in lists.
         */
        ExperimentSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            status: components["schemas"]["ExperimentStatus"];
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Summary Metrics */
            summary_metrics?: {
                [key: string]: unknown;
            } | null;
            /** Mlflow Run Id */
            mlflow_run_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageUrlOut
         * @description A short-lived, browser-reachable URL for one stored scan image.
         *
         *     Returned by ``GET /batches/{id}/image-urls`` so the client can render the
         *     original image (and overlay normalized bounding boxes) without the bytes
         *     ever traversing the API process. ``expires_at`` lets the client refetch
         *     before the presigned URL lapses.
         */
        ImageUrlOut: {
            /**
             * Image Id
             * Format: uuid
             */
            image_id: string;
            /** Url */
            url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** InferenceOut */
        InferenceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            backend: components["schemas"]["ModelBackend"];
            /** Latency Ms */
            latency_ms?: number | null;
            /** Error */
            error?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Detections */
            detections?: components["schemas"]["SeedDetectionOut"][];
        };
        /**
         * LocationSource
         * @enum {string}
         */
        LocationSource: "device_gps" | "manual" | "exif" | "none";
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LogoutIn */
        LogoutIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** MeOut */
        MeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            role: components["schemas"]["Role"];
            /** Is Active */
            is_active: boolean;
            /** Is Verified */
            is_verified: boolean;
            /** Last Login At */
            last_login_at?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** MessageOut */
        MessageOut: {
            /** Message */
            message: string;
        };
        /**
         * ModelBackend
         * @enum {string}
         */
        ModelBackend: "torch_local" | "roboflow" | "yolo";
        /**
         * ModelKind
         * @enum {string}
         */
        ModelKind: "detection" | "classification";
        /** ModelOut */
        ModelOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            kind: components["schemas"]["ModelKind"];
            backend: components["schemas"]["ModelBackend"];
            /** Seed Type Id */
            seed_type_id?: string | null;
            /** Artifact Uri */
            artifact_uri: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Training Metadata */
            training_metadata?: {
                [key: string]: unknown;
            } | null;
            /** Mlflow Run Id */
            mlflow_run_id?: string | null;
            status: components["schemas"]["ModelStatus"];
            /** Created By */
            created_by?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * ModelPerformanceOut
         * @description Aggregated performance for one model.
         *
         *     ``offline_metrics`` come from Postgres ``model_metrics`` (Phase 7
         *     experiment runner upserts them). ``rows`` come from ClickHouse fact
         *     tables (Phase 8); until that table exists the field is empty and
         *     ``note`` carries a human-readable degradation reason.
         */
        ModelPerformanceOut: {
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /** Offline Metrics */
            offline_metrics?: components["schemas"]["OfflineMetricOut"][];
            /** Rows */
            rows?: {
                [key: string]: unknown;
            }[];
            /** Note */
            note?: string | null;
        };
        /** ModelRegisterIn */
        ModelRegisterIn: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            kind: components["schemas"]["ModelKind"];
            backend: components["schemas"]["ModelBackend"];
            /** Artifact Uri */
            artifact_uri: string;
            /** Seed Type Id */
            seed_type_id?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Training Metadata */
            training_metadata?: {
                [key: string]: unknown;
            } | null;
            /** Mlflow Run Id */
            mlflow_run_id?: string | null;
        };
        /**
         * ModelStatus
         * @enum {string}
         */
        ModelStatus: "registered" | "staging" | "production" | "archived";
        /** ModelStatusUpdateIn */
        ModelStatusUpdateIn: {
            status: components["schemas"]["ModelStatus"];
        };
        /**
         * OfflineMetricOut
         * @description One row from ``model_metrics`` — an offline-eval summary metric.
         */
        OfflineMetricOut: {
            /** Metric Name */
            metric_name: string;
            /** Metric Value */
            metric_value: number;
            /** Dataset Id */
            dataset_id?: string | null;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
        };
        /**
         * PageMeta
         * @description Pagination cursor metadata. ``page`` is 1-indexed.
         */
        PageMeta: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Has More */
            has_more: boolean;
        };
        /** Page[ApiKeyOut] */
        Page_ApiKeyOut_: {
            /** Data */
            data: components["schemas"]["ApiKeyOut"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** Page[BatchOut] */
        Page_BatchOut_: {
            /** Data */
            data: components["schemas"]["BatchOut"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** Page[DatasetItemOut] */
        Page_DatasetItemOut_: {
            /** Data */
            data: components["schemas"]["DatasetItemOut"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** Page[DatasetOut] */
        Page_DatasetOut_: {
            /** Data */
            data: components["schemas"]["DatasetOut"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** Page[ExperimentSummaryOut] */
        Page_ExperimentSummaryOut_: {
            /** Data */
            data: components["schemas"]["ExperimentSummaryOut"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** Page[ModelOut] */
        Page_ModelOut_: {
            /** Data */
            data: components["schemas"]["ModelOut"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** Page[UserListOut] */
        Page_UserListOut_: {
            /** Data */
            data: components["schemas"]["UserListOut"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name?: string | null;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "ai_developer" | "end_user";
        /** RoleUpdateIn */
        RoleUpdateIn: {
            role: components["schemas"]["Role"];
        };
        /** ScanImageOut */
        ScanImageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Storage Key */
            storage_key: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Inferences */
            inferences?: components["schemas"]["InferenceOut"][];
        };
        /** SeedDetectionOut */
        SeedDetectionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Seed Type Id */
            seed_type_id?: string | null;
            quality?: components["schemas"]["SeedQuality"] | null;
            /** Confidence */
            confidence: string;
            /** Detection Confidence */
            detection_confidence?: string | null;
            /** Box X Norm */
            box_x_norm: string;
            /** Box Y Norm */
            box_y_norm: string;
            /** Box W Norm */
            box_w_norm: string;
            /** Box H Norm */
            box_h_norm: string;
            /** Area Px */
            area_px?: number | null;
            /** Width Px */
            width_px?: number | null;
            /** Height Px */
            height_px?: number | null;
            /** Aspect Ratio */
            aspect_ratio?: string | null;
        };
        /**
         * SeedQuality
         * @enum {string}
         */
        SeedQuality: "good" | "bad";
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** TrafficSplitEntryIn */
        TrafficSplitEntryIn: {
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /** Weight */
            weight: number;
            /** Valid From */
            valid_from?: string | null;
            /** Valid Until */
            valid_until?: string | null;
        };
        /** TrafficSplitOut */
        TrafficSplitOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["ModelKind"];
            /** Seed Type Id */
            seed_type_id?: string | null;
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /** Weight */
            weight: number;
            /** Is Active */
            is_active: boolean;
            /** Valid From */
            valid_from?: string | null;
            /** Valid Until */
            valid_until?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * TrafficSplitReplaceIn
         * @description Atomic replacement of all active splits for ``(kind, seed_type_id)``.
         */
        TrafficSplitReplaceIn: {
            kind: components["schemas"]["ModelKind"];
            /** Seed Type Id */
            seed_type_id?: string | null;
            /** Entries */
            entries: components["schemas"]["TrafficSplitEntryIn"][];
        };
        /** UserListOut */
        UserListOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            role: components["schemas"]["Role"];
            /** Is Active */
            is_active: boolean;
            /** Is Verified */
            is_verified: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyEmailIn */
        VerifyEmailIn: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bootstrap_admin_api_v1_auth_bootstrap_admin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapAdminIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MessageOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_api_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MessageOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TokenPair_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TokenPair_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MessageOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_login_api_v1_auth_oauth__provider__login_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_callback_api_v1_auth_oauth__provider__callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TokenPair_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserListOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_api_v1_users__user_id__role_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_keys_api_v1_api_keys_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ApiKeyOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_key_api_v1_api_keys_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ApiKeyOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_key_api_v1_api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["ModelKind"] | null;
                status?: components["schemas"]["ModelStatus"] | null;
                seed_type_id?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ModelOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_model_api_v1_models_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelRegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ModelOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_api_v1_models__model_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ModelOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_status_api_v1_models__model_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelStatusUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ModelOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_performance_api_v1_models__model_id__performance_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ModelPerformanceOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_splits_api_v1_traffic_splits_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["ModelKind"] | null;
                seed_type_id?: string | null;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_TrafficSplitOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_splits_api_v1_traffic_splits_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrafficSplitReplaceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_TrafficSplitOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_v1_analyze_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_api_v1_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_BatchOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_api_v1_batches_get: {
        parameters: {
            query?: {
                supplier_id?: string | null;
                country_code?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BatchOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_api_v1_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_BatchDetailOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_image_urls_api_v1_batches__batch_id__image_urls_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_ImageUrlOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_v1_datasets_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DatasetOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dataset_api_v1_datasets_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DatasetOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_api_v1_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DatasetOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_v1_datasets__dataset_id__items_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DatasetItemOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_items_api_v1_datasets__dataset_id__items_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetItemsBulkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DatasetItemsAddedOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_experiments_api_v1_experiments_get: {
        parameters: {
            query?: {
                model_id?: string | null;
                dataset_id?: string | null;
                status?: components["schemas"]["ExperimentStatus"] | null;
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ExperimentSummaryOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_experiment_api_v1_experiments_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExperimentSummaryOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_api_v1_experiments__experiment_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExperimentDetailOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
