"""baseline

Creates the entire OLTP schema in a single revision: extensions, ENUM types,
tables, constraints, and indexes (including partial uniques).

This is intentionally NOT autogenerated — autogenerate skips partial unique
indexes, expression indexes (LOWER(name)), and several CHECK constraints we
require. The migration is hand-rolled to match `infrastructure/db/models.py`
1:1.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-04-27 00:00:00.000000
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


# ── ENUM types ──────────────────────────────────────────────────────────────

USER_ROLE_VALUES = ("admin", "ai_developer", "end_user")
BATCH_STATUS_VALUES = ("pending", "running", "succeeded", "failed", "partial")
BATCH_SOURCE_VALUES = ("api", "web", "sdk")
LOCATION_SOURCE_VALUES = ("device_gps", "manual", "exif", "none")
MODEL_KIND_VALUES = ("detection", "classification")
MODEL_BACKEND_VALUES = ("torch_local", "roboflow", "yolo")
MODEL_STATUS_VALUES = ("registered", "staging", "production", "archived")
SEED_QUALITY_VALUES = ("good", "bad")
EXPERIMENT_STATUS_VALUES = ("pending", "running", "succeeded", "failed")


def _enum(name: str, values: tuple[str, ...]) -> postgresql.ENUM:
    """Build a Postgres ENUM type with create_type=False so we control DDL emission."""
    return postgresql.ENUM(*values, name=name, create_type=False)


def upgrade() -> None:
    # Extensions ----------------------------------------------------------------
    op.execute('CREATE EXTENSION IF NOT EXISTS "citext"')

    # ENUM types ----------------------------------------------------------------
    bind = op.get_bind()
    for name, values in [
        ("user_role", USER_ROLE_VALUES),
        ("batch_status", BATCH_STATUS_VALUES),
        ("batch_source", BATCH_SOURCE_VALUES),
        ("location_source", LOCATION_SOURCE_VALUES),
        ("model_kind", MODEL_KIND_VALUES),
        ("model_backend", MODEL_BACKEND_VALUES),
        ("model_status", MODEL_STATUS_VALUES),
        ("seed_quality", SEED_QUALITY_VALUES),
        ("experiment_status", EXPERIMENT_STATUS_VALUES),
    ]:
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)

    user_role = _enum("user_role", USER_ROLE_VALUES)
    batch_status = _enum("batch_status", BATCH_STATUS_VALUES)
    batch_source = _enum("batch_source", BATCH_SOURCE_VALUES)
    location_source = _enum("location_source", LOCATION_SOURCE_VALUES)
    model_kind = _enum("model_kind", MODEL_KIND_VALUES)
    model_backend = _enum("model_backend", MODEL_BACKEND_VALUES)
    model_status = _enum("model_status", MODEL_STATUS_VALUES)
    seed_quality = _enum("seed_quality", SEED_QUALITY_VALUES)
    experiment_status = _enum("experiment_status", EXPERIMENT_STATUS_VALUES)

    # ── users ───────────────────────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=True),
        sa.Column("full_name", sa.String(255), nullable=True),
        sa.Column("role", user_role, nullable=False, server_default=sa.text("'end_user'")),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_role", "users", ["role"])
    op.create_index("ix_users_is_active", "users", ["is_active"])

    # ── oauth_accounts ──────────────────────────────────────────────────────
    op.create_table(
        "oauth_accounts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("provider", sa.String(32), nullable=False),
        sa.Column("provider_subject", sa.String(255), nullable=False),
        sa.Column("access_token_encrypted", sa.Text(), nullable=True),
        sa.Column("refresh_token_encrypted", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("provider", "provider_subject", name="uq_oauth_provider_subject"),
        sa.CheckConstraint("provider IN ('google', 'github')", name="ck_oauth_accounts_provider_supported"),
    )
    op.create_index("ix_oauth_accounts_user_id", "oauth_accounts", ["user_id"])

    # ── refresh_tokens ──────────────────────────────────────────────────────
    op.create_table(
        "refresh_tokens",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "replaced_by_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("refresh_tokens.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("user_agent", sa.String(512), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"])
    op.create_index("ix_refresh_tokens_replaced_by_id", "refresh_tokens", ["replaced_by_id"])
    op.create_index("ix_refresh_tokens_expires_at", "refresh_tokens", ["expires_at"])
    op.create_index(
        "uq_refresh_tokens_live_hash",
        "refresh_tokens",
        ["token_hash"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )

    # ── api_keys ────────────────────────────────────────────────────────────
    op.create_table(
        "api_keys",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("key_hash", sa.String(255), nullable=False),
        sa.Column("prefix", sa.String(16), nullable=False),
        sa.Column(
            "scopes",
            postgresql.ARRAY(sa.String(64)),
            nullable=False,
            server_default=sa.text("'{}'::varchar[]"),
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("key_hash", name="uq_api_keys_key_hash"),
    )
    op.create_index("ix_api_keys_user_id", "api_keys", ["user_id"])
    op.create_index("ix_api_keys_prefix", "api_keys", ["prefix"])

    # ── audit_log ───────────────────────────────────────────────────────────
    op.create_table(
        "audit_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "actor_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("action", sa.String(64), nullable=False),
        sa.Column("target_type", sa.String(64), nullable=True),
        sa.Column("target_id", sa.String(64), nullable=True),
        sa.Column("metadata", postgresql.JSONB(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_audit_log_actor_id", "audit_log", ["actor_id"])
    op.create_index("ix_audit_log_action", "audit_log", ["action"])
    op.create_index("ix_audit_log_target_type_target_id", "audit_log", ["target_type", "target_id"])
    op.create_index("ix_audit_log_occurred_at", "audit_log", ["occurred_at"])

    # ── seed_types ──────────────────────────────────────────────────────────
    op.create_table(
        "seed_types",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("code", sa.String(32), nullable=False),
        sa.Column("display_name", sa.String(120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "default_confidence_threshold",
            sa.Numeric(5, 4),
            nullable=False,
            server_default=sa.text("0.5000"),
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("code", name="uq_seed_types_code"),
        sa.CheckConstraint(
            "default_confidence_threshold >= 0 AND default_confidence_threshold <= 1",
            name="ck_seed_types_default_confidence_threshold_range",
        ),
    )

    # ── suppliers ───────────────────────────────────────────────────────────
    op.create_table(
        "suppliers",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", postgresql.CITEXT(), nullable=False),
        sa.Column("slug", sa.String(160), nullable=False),
        sa.Column("is_global", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "created_by_user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("metadata", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("slug", name="uq_suppliers_slug"),
        sa.CheckConstraint(
            "(is_global AND created_by_user_id IS NULL) "
            "OR (NOT is_global AND created_by_user_id IS NOT NULL)",
            name="ck_suppliers_global_xor_owner",
        ),
    )
    op.create_index(
        "uq_suppliers_global_lower_name",
        "suppliers",
        [sa.text("lower(name)")],
        unique=True,
        postgresql_where=sa.text("is_global"),
    )
    op.create_index(
        "uq_suppliers_private_owner_lower_name",
        "suppliers",
        ["created_by_user_id", sa.text("lower(name)")],
        unique=True,
        postgresql_where=sa.text("NOT is_global"),
    )
    op.create_index("ix_suppliers_is_global_is_active", "suppliers", ["is_global", "is_active"])
    op.create_index("ix_suppliers_created_by_user_id", "suppliers", ["created_by_user_id"])

    # ── model_artifacts ─────────────────────────────────────────────────────
    op.create_table(
        "model_artifacts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(160), nullable=False),
        sa.Column("version", sa.String(32), nullable=False),
        sa.Column("kind", model_kind, nullable=False),
        sa.Column("backend", model_backend, nullable=False),
        sa.Column(
            "seed_type_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("seed_types.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column("artifact_uri", sa.String(512), nullable=False),
        sa.Column("config", postgresql.JSONB(), nullable=True),
        sa.Column("training_metadata", postgresql.JSONB(), nullable=True),
        sa.Column("mlflow_run_id", sa.String(64), nullable=True),
        sa.Column(
            "status",
            model_status,
            nullable=False,
            server_default=sa.text("'registered'"),
        ),
        sa.Column(
            "created_by",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("name", "version", name="uq_model_artifacts_name_version"),
    )
    op.create_index(
        "uq_model_artifacts_one_prod_per_kind_seed",
        "model_artifacts",
        ["kind", "seed_type_id"],
        unique=True,
        postgresql_where=sa.text("status = 'production'"),
    )
    op.create_index("ix_model_artifacts_seed_type_id", "model_artifacts", ["seed_type_id"])
    op.create_index("ix_model_artifacts_created_by", "model_artifacts", ["created_by"])
    op.create_index("ix_model_artifacts_status", "model_artifacts", ["status"])
    op.create_index("ix_model_artifacts_kind", "model_artifacts", ["kind"])

    # ── datasets ────────────────────────────────────────────────────────────
    op.create_table(
        "datasets",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_by",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("name", name="uq_datasets_name"),
    )
    op.create_index("ix_datasets_created_by", "datasets", ["created_by"])

    # ── dataset_items ───────────────────────────────────────────────────────
    op.create_table(
        "dataset_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "dataset_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("datasets.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("image_storage_key", sa.String(512), nullable=False),
        sa.Column("ground_truth", postgresql.JSONB(), nullable=True),
        sa.Column("checksum", sa.String(128), nullable=True),
        sa.UniqueConstraint(
            "dataset_id",
            "image_storage_key",
            name="uq_dataset_items_dataset_storage_key",
        ),
    )
    op.create_index("ix_dataset_items_dataset_id", "dataset_items", ["dataset_id"])

    # ── model_metrics ───────────────────────────────────────────────────────
    op.create_table(
        "model_metrics",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "model_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("model_artifacts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "dataset_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("datasets.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("metric_name", sa.String(64), nullable=False),
        sa.Column("metric_value", sa.Numeric(12, 6), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_model_metrics_model_id_metric_name", "model_metrics", ["model_id", "metric_name"])
    op.create_index("ix_model_metrics_dataset_id", "model_metrics", ["dataset_id"])

    # ── traffic_splits ──────────────────────────────────────────────────────
    op.create_table(
        "traffic_splits",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("kind", model_kind, nullable=False),
        sa.Column(
            "seed_type_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("seed_types.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column(
            "model_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("model_artifacts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("weight", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("weight >= 0 AND weight <= 100", name="ck_traffic_splits_weight_range"),
    )
    op.create_index("ix_traffic_splits_kind_seed_type_id", "traffic_splits", ["kind", "seed_type_id"])
    op.create_index("ix_traffic_splits_model_id", "traffic_splits", ["model_id"])
    op.create_index("ix_traffic_splits_is_active", "traffic_splits", ["is_active"])

    # ── experiments ─────────────────────────────────────────────────────────
    op.create_table(
        "experiments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(160), nullable=False),
        sa.Column("status", experiment_status, nullable=False, server_default=sa.text("'pending'")),
        sa.Column(
            "model_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("model_artifacts.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "dataset_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("datasets.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("summary_metrics", postgresql.JSONB(), nullable=True),
        sa.Column("mlflow_run_id", sa.String(64), nullable=True),
        sa.Column(
            "created_by",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_experiments_model_id", "experiments", ["model_id"])
    op.create_index("ix_experiments_dataset_id", "experiments", ["dataset_id"])
    op.create_index("ix_experiments_created_by", "experiments", ["created_by"])
    op.create_index("ix_experiments_status", "experiments", ["status"])

    # ── experiment_results ──────────────────────────────────────────────────
    op.create_table(
        "experiment_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "experiment_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("experiments.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "dataset_item_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("dataset_items.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("predicted_boxes", postgresql.JSONB(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
    )
    op.create_index("ix_experiment_results_experiment_id", "experiment_results", ["experiment_id"])
    op.create_index("ix_experiment_results_dataset_item_id", "experiment_results", ["dataset_item_id"])

    # ── scan_batches ────────────────────────────────────────────────────────
    op.create_table(
        "scan_batches",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "supplier_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("suppliers.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("status", batch_status, nullable=False, server_default=sa.text("'pending'")),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("source", batch_source, nullable=False, server_default=sa.text("'api'")),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("location_source", location_source, nullable=True),
        sa.Column("gps_lat", sa.Numeric(9, 6), nullable=True),
        sa.Column("gps_long", sa.Numeric(9, 6), nullable=True),
        sa.Column("geo_city", sa.String(120), nullable=True),
        sa.Column("geo_country_code", sa.String(2), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(gps_lat IS NULL) = (gps_long IS NULL)",
            name="ck_scan_batches_gps_lat_long_paired",
        ),
        sa.CheckConstraint(
            "gps_lat IS NULL OR (gps_lat >= -90 AND gps_lat <= 90)",
            name="ck_scan_batches_gps_lat_range",
        ),
        sa.CheckConstraint(
            "gps_long IS NULL OR (gps_long >= -180 AND gps_long <= 180)",
            name="ck_scan_batches_gps_long_range",
        ),
        sa.CheckConstraint(
            "geo_country_code IS NULL OR geo_country_code ~ '^[A-Z]{2}$'",
            name="ck_scan_batches_geo_country_code_iso2",
        ),
    )
    op.create_index("ix_scan_batches_user_id_submitted_at", "scan_batches", ["user_id", "submitted_at"])
    op.create_index(
        "ix_scan_batches_supplier_id",
        "scan_batches",
        ["supplier_id"],
        postgresql_where=sa.text("supplier_id IS NOT NULL"),
    )
    op.create_index("ix_scan_batches_status", "scan_batches", ["status"])
    op.create_index("ix_scan_batches_geo_country_code", "scan_batches", ["geo_country_code"])

    # ── scan_images ─────────────────────────────────────────────────────────
    op.create_table(
        "scan_images",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "batch_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("scan_batches.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(512), nullable=False),
        sa.Column("content_type", sa.String(64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("batch_id", "storage_key", name="uq_scan_images_batch_storage_key"),
        sa.CheckConstraint("size_bytes > 0", name="ck_scan_images_size_bytes_positive"),
    )
    op.create_index("ix_scan_images_batch_id", "scan_images", ["batch_id"])
    op.create_index("ix_scan_images_sha256", "scan_images", ["sha256"])

    # ── inferences ──────────────────────────────────────────────────────────
    op.create_table(
        "inferences",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "image_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("scan_images.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "model_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("model_artifacts.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("backend", model_backend, nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("image_id", "model_id", name="uq_inferences_image_model"),
    )
    op.create_index("ix_inferences_image_id", "inferences", ["image_id"])
    op.create_index("ix_inferences_model_id", "inferences", ["model_id"])
    op.create_index("ix_inferences_occurred_at", "inferences", ["occurred_at"])

    # ── seed_detections ─────────────────────────────────────────────────────
    op.create_table(
        "seed_detections",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "inference_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("inferences.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "seed_type_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("seed_types.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column("quality", seed_quality, nullable=True),
        sa.Column("confidence", sa.Numeric(5, 4), nullable=False),
        sa.Column("detection_confidence", sa.Numeric(5, 4), nullable=True),
        sa.Column("box_x_norm", sa.Numeric(7, 6), nullable=False),
        sa.Column("box_y_norm", sa.Numeric(7, 6), nullable=False),
        sa.Column("box_w_norm", sa.Numeric(7, 6), nullable=False),
        sa.Column("box_h_norm", sa.Numeric(7, 6), nullable=False),
        sa.Column("area_px", sa.Integer(), nullable=True),
        sa.Column("width_px", sa.Integer(), nullable=True),
        sa.Column("height_px", sa.Integer(), nullable=True),
        sa.Column("aspect_ratio", sa.Numeric(8, 4), nullable=True),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_seed_detections_confidence_range"),
        sa.CheckConstraint(
            "detection_confidence IS NULL OR "
            "(detection_confidence >= 0 AND detection_confidence <= 1)",
            name="ck_seed_detections_detection_confidence_range",
        ),
        sa.CheckConstraint(
            "box_x_norm >= 0 AND box_x_norm <= 1 "
            "AND box_y_norm >= 0 AND box_y_norm <= 1 "
            "AND box_w_norm > 0 AND box_w_norm <= 1 "
            "AND box_h_norm > 0 AND box_h_norm <= 1",
            name="ck_seed_detections_bbox_normalized",
        ),
    )
    op.create_index("ix_seed_detections_inference_id", "seed_detections", ["inference_id"])
    op.create_index(
        "ix_seed_detections_seed_type_quality",
        "seed_detections",
        ["seed_type_id", "quality"],
    )


def downgrade() -> None:
    # Drop tables in reverse dependency order.
    for table in (
        "seed_detections",
        "inferences",
        "scan_images",
        "scan_batches",
        "experiment_results",
        "experiments",
        "traffic_splits",
        "model_metrics",
        "dataset_items",
        "datasets",
        "model_artifacts",
        "suppliers",
        "seed_types",
        "audit_log",
        "api_keys",
        "refresh_tokens",
        "oauth_accounts",
        "users",
    ):
        op.drop_table(table)

    # Drop ENUM types.
    bind = op.get_bind()
    for name in (
        "experiment_status",
        "seed_quality",
        "model_status",
        "model_backend",
        "model_kind",
        "location_source",
        "batch_source",
        "batch_status",
        "user_role",
    ):
        postgresql.ENUM(name=name).drop(bind, checkfirst=True)
