"""batch share token

Adds the nullable ``share_token`` column to ``scan_batches`` plus a unique
index on it (NULLs allowed; only non-null tokens must be unique). Backs the
public read-only share links: ``POST/DELETE /api/v1/batches/{id}/share`` and
``GET /api/v1/shared/{token}``.

Hand-rolled (not autogenerated) to match ``infrastructure/db/models.py``.

Revision ID: 0002_batch_share_token
Revises: 0001_baseline
Create Date: 2026-06-22 00:00:00.000000
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0002_batch_share_token"
down_revision = "0001_baseline"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "scan_batches",
        sa.Column("share_token", sa.String(length=64), nullable=True),
    )
    # Unique only over non-null tokens — many batches stay unshared (NULL).
    op.create_index(
        "uq_scan_batches_share_token",
        "scan_batches",
        ["share_token"],
        unique=True,
        postgresql_where=sa.text("share_token IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index("uq_scan_batches_share_token", table_name="scan_batches")
    op.drop_column("scan_batches", "share_token")
