flowchart TD
    M0[/Feature Maps from Backbone/] --> E[RPN: Region Proposal Network]
    E --> F[RoI Align / RoI Pooling]
    F --> G[ROI Head]
    G --> H[Classification Head]
    G --> I[BBox Regression Head]
    I --> J[CIoU Loss]
    H --> K[Final Class Label]
    I --> L[Final Bounding Box]

    subgraph Detection_Stage[Detection Stage]
        E
        F
        G
        H
        I
    end

    subgraph Output[Outputs]
        K
        L
    end
